[programs.devnet]
faucet = "7G5gNHT2T2fdb9EHY5K6FEPc6Z1mAF8M5uhURWDbsBjE"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/kk/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
