[programs.devnet]
lpusd_auction = "6KS4ho2CDvr7MGofHU6F6WJfQ5j6DL8nhBWJtkhMTzqt"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/kk/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
